### ISSUE TITLE
Create /robots.txt

### ISSUE THREAD

**Issue by mateus4k** [ufersa/plataforma-sabia#1107]
### Error:
```json
HttpException: E_ROUTE_NOT_FOUND: Route not found GET /robots.txt
    at Server._getRoute (/plataforma-sabia/api/node_modules/@adonisjs/framework/src/Server/index.js:146:13)
    at /plataforma-sabia/api/node_modules/@adonisjs/framework/src/Server/index.js:429:28
```
### Request:
```json
{}
```

**Comment by luizeboli** [comment]
This file already exists in admin package. IDK why that error happened.
