### ISSUE TITLE
Error when trying to deploy to now

### ISSUE THREAD

**Issue by lcnogueira** [ufersa/plataforma-sabia#84]
## Bug Description
Um erro ocorre ao tentar realizar um deploy para a plataforma do zeit:
```
2020-05-03T23:33:54.948Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Error","errorMessage":"Must use import to load ES Module: /var/task/node_modules/i18next-http-backend/cjs/index.js\nrequire() of ES modules is not supported.\nrequire() of /var/task/node_modules/i18next-http-backend/cjs/index.js from /var/task/node_modules/next-i18next/dist/commonjs/create-i18next-client.js is an ES module file as it is a .js file whose nearest parent package.json contains \"type\": \"module\" which defines all .js files in that package scope as ES modules.\nInstead rename index.js to end in .cjs, change the requiring code to use import(), or remove \"type\": \"module\" from /var/task/node_modules/i18next-http-backend/package.json.\n","code":"ERR_REQUIRE_ESM","stack":["Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /var/task/node_modules/i18next-http-backend/cjs/index.js","require() of ES modules is not supported.","require() of /var/task/node_modules/i18next-http-backend/cjs/index.js from /var/task/node_modules/next-i18next/dist/commonjs/create-i18next-client.js is an ES module file as it is a .js file whose nearest parent package.json contains \"type\": \"module\" which defines all .js files in that package scope as ES modules.","Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove \"type\": \"module\" from /var/task/node_modules/i18next-http-backend/package.json.","","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1174:13)","    at Module.load (internal/modules/cjs/loader.js:1002:32)","    at Function.Module._load (internal/modules/cjs/loader.js:901:14)","    at Module.require (internal/modules/cjs/loader.js:1044:19)","    at require (internal/modules/cjs/helpers.js:77:18)","    at Object.<anonymous> (/var/task/node_modules/next-i18next/dist/commonjs/create-i18next-client.js:18:50)","    at Module._compile (internal/modules/cjs/loader.js:1158:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)","    at Module.load (internal/modules/cjs/loader.js:1002:32)","    at Function.Module._load (internal/modules/cjs/loader.js:901:14)"]}
Unknown application error occurred
```
## Steps to reproduce
1) Configure a CLI do zeit na sua máquina: 
2) Tente realizar um deploy do código para a platforma:
```
now --prod
```

**Comment by lcnogueira** [comment]
FYI, @nicholasio 

Tem outros apps/libs com o mesmo problema na hora do deploy pro vercel/zeitjs. O problema ocorre porque a plataforma deles não suporta EcmaScript Module (ESM) no momento e, pelo menos uma das libs que é dependência da `next-i18next` tenta importar um ESM. Por isso, o erro:
```
[...]
2020-05-05T14:48:46.108Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Error","errorMessage":"Must use import to load ES Module: /var/task/node_modules/i18next-http-backend/cjs/index.js\nrequire() of ES modules is not supported.\nrequire() of /var/task/node_modules/i18next-http-backend/cjs/index.js from /var/task/node_modules/next-i18next/dist/commonjs/create-i18next-client.js is an ES module file as it is a .js file whose nearest parent package.json contains \"type\": \"module\" which defines all .js files in that package scope as ES modules.\nInstead rename index.js to end in .cjs, change the requiring code to use import(), or remove \"type\": \"module\" from /var/task/node_modules/i18next-http-backend/package.json.\n","code":"ERR_REQUIRE_ESM","stack":["Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /var/task/node_modules/i18next-http-backend/cjs/index.js","require() of ES modules is not supported.","require() of /var/task/node_modules/i18next-http-backend/cjs/index.js from /var/task/node_modules/next-i18next/dist/commonjs/create-i18next-client.js is an ES module file as it is a .js file whose nearest parent package.json contains \"type\": \"module\" which defines all .js files in that package scope as ES modules.","Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove \"type\": \"module\" from /var/task/node_modules/i18next-http-backend/package.json.","","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1174:13)","    at Module.load (internal/modules/cjs/loader.js:1002:32)","    at Function.Module._load (internal/modules/cjs/loader.js:901:14)","    at Module.require (internal/modules/cjs/loader.js:1044:19)","    at require (internal/modules/cjs/helpers.js:77:18)","    at Object.<anonymous> (/var/task/node_modules/next-i18next/dist/commonjs/create-i18next-client.js:18:50)","    at Module._compile (internal/modules/cjs/loader.js:1158:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)","    at Module.load (internal/modules/cjs/loader.js:1002:32)","    at Function.Module._load (internal/modules/cjs/loader.js:901:14)"]}
Unknown application error occurred
Error
[...]
```

De acordo com o pessoal do Vercel, [o suporte a esses arquivos vai ser realizado uma vez que o ECMAScript Module (ESM) for estável no node.
](https://github.com/zeit/now/issues/3337#issuecomment-556141731)

Uma saída, seria setar a flagh `--experimental-modules` , visto que o NodeJs 12 (versão máxima e a padrão suportada pelo `now`) suporta ESM modules. Porém, o [now não suporta o uso dessas flags](https://github.com/zeit/now/issues/2854#issuecomment-520053188). Então, um workaround (no próprio link anterior) seria renomear os arquivos `.mjs` para `.js`, mas nós não temos controle sobre esses arquivos (até onde sei...teria?).

Uma saída então, foi setar a engine para usar o node 10 ao invés do 12 (aparentemente, o suporte passou a ser padrão no node 14, mas, como disse acima, o zeitjs não oferece a possibilidade de usá-lo)
```
"engines": {
    "node": "10.x"
  },
```
Com isso, a mensagem de erro desaparece, porém, o erro continua:
```
2020-05-05T01:48:02.636Z	undefined	ERROR	Uncaught Exception	{"errorType":"Error","errorMessage":"ENOENT: no such file or directory, scandir '/var/task/public/static/locales/pt'","code":"ENOENT","errno":-2,"syscall":"scandir","path":"/var/task/public/static/locales/pt","stack":["Error: ENOENT: no such file or directory, scandir '/var/task/public/static/locales/pt'","    at Object.readdirSync (fs.js:790:3)","    at getAllNamespaces (/var/task/node_modules/next-i18next/dist/commonjs/config/create-config.js:111:19)","    at createConfig (/var/task/node_modules/next-i18next/dist/commonjs/config/create-config.js:116:27)","    at new NextI18Next (/var/task/node_modules/next-i18next/dist/commonjs/index.js:53:48)","    at Object.4JyM (/var/task/.next/serverless/pages/_error.js:1823:18)","    at __webpack_require__ (/var/task/.next/serverless/pages/_error.js:23:31)","    at Module.1TCz (/var/task/.next/serverless/pages/_error.js:1476:18)","    at __webpack_require__ (/var/task/.next/serverless/pages/_error.js:23:31)","    at Module.3PTK (/var/task/.next/serverless/pages/_error.js:1633:17)","    at __webpack_require__ (/var/task/.next/serverless/pages/_error.js:23:31)"]}
Unknown application error occurred
Error
```
No final das contas, o problema permanece o mesmo: o zeitjs não conseguiria carregar os arquivos `.json` com as traduções lá de dentro do `static/locales/pt`. Por isso, não sei bem se esse workaround de setar o node 10 seria a melhor opção, visto que, no final das contas, o erro continua.

Tem uma  thread lá no github da bilioteca que trata bastante sobre o assunto (e para a qual as outras apontam): https://github.com/isaachinman/next-i18next/issues/274. **Ainda tentando encontrar uma solução através dela...**

**Comment by nicholasio** [comment]
Não creio que isso seja um grande problema, não necessariamente nós vamos usar o `now` em produção. Se usarmos nosso próprio servidor conseguimos rodar sem problemas. Eu não tive nenhum problema em dar um build localmente e iniciar o servidor em modo produção.

**Comment by nicholasio** [comment]
O ideal seria termos nosso "staging" oficial, mas vai depender dos recursos para serviços.

**Comment by lcnogueira** [comment]
Então, mas por hora, seria interessante deixar em um servidor, não acha? até para testarmos algumas coisas em "produção". Ex.: o uso dos componentes do algolia se comportam bem melhor no servidor. Acha que vale a pena investir um pouco mais para tentar resolver ou melhor deixar por hora?

**Comment by lcnogueira** [comment]
@nicholasio , o problema com a plataforma do `now` persiste. 

Atualizei a lib, porque fizeram um ajuste (no última dia 04/05) para deixar de usar imports de EcmaScript modules (ESM) e passaram a importar do diretório dos CommonJS modules. Com isso, vai evitar problemas em possíveis plataformas que não suportem ESM (como o `now`). Por isso, e **já que não traz nenhum prejuízo, acho que seria bom mantermos a atualização da lib**.

Porém, agora o problema é que os arquivos dentro do `public/static/locales/pt` não são reconhecidos. Porém, isso é algo especfico da plataforma. [Outras pessoas estão com o mesmo problema](https://github.com/isaachinman/next-i18next/issues/274#issuecomment-624533945).

Como já estamos com um [novo ambiente](https://plataforma-sabia.herokuapp.com/), isso não é um problema. De qualquer modo, abri uma [discussão lá no repositório do now](https://github.com/zeit/now/discussions/4271). Se resolverem mais adiante, ótimo, porque ficamos com os 2 ambientes (vou acompanhando e deixo vocês informados).

Como a situação é essa, acho que podemos fazer o merge da PR #89 e consequentemente concluir essa issue.

**Comment by nicholasio** [comment]
@lcnogueira concordo!
